### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tsuchida-hikaru** [Tsuchida-hikaru/furima-29774#8]
- [フリマアプリへのリンク](https://furima-29774.herokuapp.com/products)
- Basic認証のIDとパスワード 
    - ID : admin
    - password : 1234
- 出品者用のメールアドレスとパスワード
    - mail : tarou@tarou.com
    - password : tarou123
- 購入者用のメールアドレスとパスワード
    - mail : jirou@jirou.com
    - password : jirou123
- 購入用カードの番号・期限・セキュリティコード
    - number : 4242424242424242
    - expiration : 西暦20年以上ならいつでもOK
    - CVC : 123

ご精査の程をよろしくお願い致します。

**Comment by mutorisa** [comment]
土田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨

※最終課題説明文には、カード情報の有効期限を指定してご記載していただきますようお願いします。


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
